#!/bin/bash

if [ -z ${ACCESS_KEY_ID} ]; then
  echo "Error: Please specify the ACCESS_KEY_ID environment variable"
  exit 1
fi

if [ -z ${SECRET_ACCESS_KEY} ]; then
  echo "Error: Please specify the SECRET_ACCESS_KEY environment variable"
  exit 1
fi

# These are dependencies for the
# AWS Volume Cleaner script
pip install boto3
pip install retrying

if [ -z ${REGION} ]; then
  REGION="us-west-2"
fi



# The command to run the AWS Volume Cleaner script
./services/_scripts/external-volumes/volclean.py -y -v -r ${REGION} \
 -k ${ACCESS_KEY_ID} -s ${SECRET_ACCESS_KEY} \
 --ignore-metrics --tags "Name:^integration-test-dcos-ui-${TEST_UUID}"
